axis_1 = {
    "startText": "Particulars",
    "endText": "CLOSING BALANCE",
    "startEndDefColumn": "C",
    "delRefText1": "OPENING BALANCE",
    "delRefText2": "TRANSACTION TOTAL",
    "delRefText3": "CLOSING BALANCE",
    "deleteFlagRefColumn": "C",
    "stringAlignColumn1": "C",
    "stringAlignColumn2": "G",
    "dateConversionColumn": "A",
    "refHeaderText1": "Tran Date",
    "refHeaderText2": "Chq No",
    "refHeaderText3": "Particulars",
    "refHeaderText4": "Debit",
    "refHeaderText5": "Credit",
    "refHeaderText6": "Balance",
    "headerText1": "Transaction_Date",
    "headerText2": "ChequeNo_RefNo",
    "headerText3": "Narration",
    "headerText4": "Withdrawal",
    "headerText5": "Deposit",
    "headerText6": "Balance",
    "deleteColumnRefText": "Init.Br",
    "columns": ["Sl.No.", "Transaction_Date", "Value_Date", "ChequeNo_RefNo", "Narration", "Deposit", "Withdrawal", "Balance"],
    "negativeValueColumnRefText1": "Withdrawal",
    "headerTextToEmptyCellToNone1": "Value_Date",
    "headerTextToEmptyCellToNone2": "ChequeNo_RefNo",
    "headerTextToEmptyCellToNone3": "Withdrawal",
    "headerTextToEmptyCellToNone4": "Deposit",
}
canara_1 = {
    "startText": "TRANS",
    "endText": "UNLESS THE CONSTITUENT BRINGS TO THE NOTICE OF THE BANK",
    "startEndRefColumn": "A",
    "mergHeaderColumn1": "A",
    "mergHeaderColumn2": "B",
    "duplicateHeaderTxt1": "TRANS",
    "duplicateHeaderTxt2": "DATE",
    "duplicateHeaderRefColumn": "A",
    "startText2": "TRANS DATE",
    "endText2": "Statement Summary :",
    "pgNoLength": 5,
    "refColumnToDeletePgNoRow": "A",
    "refColumnToMerg": "A",
    "columnToMerg1": "E",
    "refColumnToDeleteNoneRows": "A",
    "fromColumn": "I",
    "toColumn": "H",
    "stringAlignColumn": "E",
    "refTextToDeleteRow": "B/F",
    "refColumnToDeleteRow": "E",
    "dateConversionColumn1": "A",
    "dateConversionColumn2": "B",
    "deleteColumnRefText1": "BRANCH",
    "refHeaderText1": "TRANS DATE",
    "refHeaderText2": "VALUE DATE",
    "refHeaderText3": "REF/CHQ.NO",
    "refHeaderText4": "DESCRIPTION",
    "refHeaderText5": "WITHDRAWS",
    "refHeaderText6": "DEPOSIT",
    "refHeaderText7": "BALANCE",
    "headerText1": "Transaction_Date",
    "headerText2": "Value_Date",
    "headerText3": "ChequeNo_RefNo",
    "headerText4": "Narration",
    "headerText5": "Withdrawal",
    "headerText6": "Deposit",
    "headerText7": "Balance",
    "negativeValueColumnRefText1": "Withdrawal",
}
